# Generated by Django 4.0.2 on 2022-02-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0002_rename_pagemodel_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='isDropdown',
            field=models.BooleanField(default=False),
        ),
    ]
