# Generated by Django 4.0.2 on 2022-02-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0003_page_isdropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='isDropdown',
            field=models.BooleanField(default=False, verbose_name='Place in dropdown menu'),
        ),
    ]
