# Generated by Django 4.0.2 on 2022-02-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0004_alter_page_isdropdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Oldal', 'verbose_name_plural': 'Oldalak'},
        ),
    ]
