# Generated by Django 4.2 on 2023-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0005_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='isDropdown',
            field=models.BooleanField(default=False, verbose_name='Tedd az egyebek menübe'),
        ),
    ]
