# Generated by Django 4.2 on 2023-04-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0006_alter_page_isdropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
