# Generated by Django 4.2 on 2023-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navpages', '0007_remove_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
