# Generated by Django 4.2 on 2023-04-18 07:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', tinymce.models.HTMLField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/')),
                ('sign', models.CharField(default='TheOld - Crafters', max_length=30)),
                ('categorys', models.ManyToManyField(to='news.category')),
            ],
            options={
                'verbose_name': 'Hír',
                'verbose_name_plural': 'Hírek',
            },
        ),
    ]
